package com.tag.sysTagRep.service;

import com.tag.sysTagRep.config.DatabaseConnection;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class FacturaServiceRideTest {

    private String dbName;
    private Connection con;

    @BeforeEach
    void setUp() throws Exception {
        dbName = "testdb_ride_" + UUID.randomUUID().toString().replace("-", "");
        con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "");
        DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
        crearTablas(con);
        insertarDatos();
    }

    @AfterEach
    void tearDown() throws Exception {
        if (con != null && !con.isClosed()) con.close();
        DatabaseConnection.resetToDefault();
    }

    private void crearTablas(Connection con) throws Exception {
        try (Statement st = con.createStatement()) {
            st.execute("CREATE TABLE empresa (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ruc VARCHAR(13), razon_social VARCHAR(150), sucursal VARCHAR(150), direccion_calle_principal VARCHAR(150), direccion_calle_secundaria VARCHAR(150), telefono VARCHAR(20), celular VARCHAR(20), correo VARCHAR(100), logo_url VARCHAR(255), agente_retencion VARCHAR(20), resolucion VARCHAR(50), estado BOOLEAN)");
            st.execute("CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR(100), identificacion VARCHAR(13), direccion VARCHAR(100), correo VARCHAR(60), telefono VARCHAR(10), celular VARCHAR(10), fecha_registro TIMESTAMP, estado BOOLEAN)");
            st.execute("CREATE TABLE factura_registro (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, empresa_id INT, cliente_id INT, fecha TIMESTAMP, codigo VARCHAR(30), forma_pago VARCHAR(30), subtotal DECIMAL(10,2), iva DECIMAL(10,2), descuento DECIMAL(10,2), total DECIMAL(10,2), clave_acceso VARCHAR(49), num_comprobante VARCHAR(20), ambiente_sri VARCHAR(10), estado_sri VARCHAR(20), fecha_registro TIMESTAMP)");
            st.execute("CREATE TABLE factura_detalle (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, factura_registro_id INT, inventario_id INT, codigo VARCHAR(30), descripcion VARCHAR(100), cantidad INT, precio_unitario DECIMAL(10,2), precio_total DECIMAL(10,2), subtotal DECIMAL(10,2), iva DECIMAL(10,2), descuento DECIMAL(10,2), total DECIMAL(10,2), fecha_registro TIMESTAMP)");
            st.execute("CREATE TABLE comprobantes_electronicos (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nota_venta_id INT, tipo_comprobante VARCHAR(2), clave_acceso VARCHAR(49), numero_comprobante VARCHAR(20), ambiente VARCHAR(10), estado_sri VARCHAR(20), mensaje_sri VARCHAR(500), xml_generado CLOB, xml_autorizado CLOB, numero_autorizacion VARCHAR(49), fecha_autorizacion TIMESTAMP)");
        }
    }

    private void insertarDatos() throws Exception {
        try (Statement st = con.createStatement()) {
            st.execute("INSERT INTO empresa(id, ruc, razon_social, sucursal, direccion_calle_principal, direccion_calle_secundaria, telefono, celular, correo, estado) VALUES (1, '1790000000001', 'TAG REPUESTOS', 'Matriz', 'Av. Principal', 'Secundaria', '0999999999', '0999999999', 'tag@example.com', TRUE)");
            st.execute("INSERT INTO cliente(id, nombre, identificacion, direccion, correo, telefono, celular, fecha_registro, estado) VALUES (1, 'Cliente Prueba', '1790000000002', 'Quito', 'cliente@example.com', '0988888888', '0988888888', CURRENT_TIMESTAMP, TRUE)");
            st.execute("INSERT INTO factura_registro(id, empresa_id, cliente_id, fecha, codigo, forma_pago, subtotal, iva, descuento, total, clave_acceso, num_comprobante, ambiente_sri, estado_sri, fecha_registro) VALUES (1, 1, 1, CURRENT_TIMESTAMP, '001', 'Efectivo', 53.92, 8.09, 0.00, 62.01, '1234567890123456789012345678901234567890123456789', '001-001-000000001', 'PRUEBAS', 'PENDIENTE', CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO factura_detalle(id, factura_registro_id, inventario_id, codigo, descripcion, cantidad, precio_unitario, precio_total, subtotal, iva, descuento, total, fecha_registro) VALUES (1, 1, 1, '001', 'Aceite 5W30', 2, 30.00, 60.00, 60.00, 9.00, 0.00, 69.00, CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO comprobantes_electronicos(id, nota_venta_id, tipo_comprobante, clave_acceso, numero_comprobante, ambiente, estado_sri) VALUES (1, NULL, '01', '1234567890123456789012345678901234567890123456789', '001-001-000000001', 'PRUEBAS', 'PENDIENTE')");
        }
    }

    @Test
    void regenerarRide_facturaPendienteAutorizada_pdfContieneNumeroAutorizacion() throws Exception {
        String clave = "1234567890123456789012345678901234567890123456789";
        String numAut = "0987654321098765432109876543210987654321098765432";

        Path dir = Files.createTempDirectory("ride_test");
        FacturaService service = new FacturaService();
        String rutaPDF = service.regenerarRide(clave, numAut, "2026-08-12T10:00:00-05:00", dir.toFile());

        assertNotNull(rutaPDF, "regenerarRide debe devolver la ruta del PDF");
        File pdf = new File(rutaPDF);
        assertTrue(pdf.exists(), "El RIDE regenerado debe existir en " + rutaPDF);
        assertTrue(pdf.length() > 0, "El RIDE debe tener contenido");

        String txt = extraerTexto(rutaPDF);
        String normalizado = txt.replaceAll("\\s+", "");
        assertTrue(normalizado.contains(numAut.replaceAll("\\s+", "")) || normalizado.contains(clave),
                "El RIDE regenerado debe contener el número de autorización o la clave");
    }

    private String extraerTexto(String rutaPDF) throws Exception {
        com.lowagie.text.pdf.PdfReader r = new com.lowagie.text.pdf.PdfReader(rutaPDF);
        try {
            return new com.lowagie.text.pdf.parser.PdfTextExtractor(r).getTextFromPage(1);
        } finally {
            r.close();
        }
    }

    @Test
    void regenerarRide_claveInexistente_retornaNull() throws Exception {
        Path dir = Files.createTempDirectory("ride_test");
        FacturaService service = new FacturaService();
        String rutaPDF = service.regenerarRide("9999999999999999999999999999999999999999999999999",
                "0987654321098765432109876543210987654321098765432", "2026-08-12T10:00:00-05:00", dir.toFile());
        assertNull(rutaPDF, "Si la factura no existe, no debe generar PDF");
    }
}
