package com.tag.sysTagRep.dao;

import com.tag.sysTagRep.config.DatabaseConnection;
import com.tag.sysTagRep.model.Cliente;
import org.junit.jupiter.api.Test;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

class ClienteDAOTest {

    private Connection getConnection() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        return DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "");
    }

    private void crearTabla(Connection con) throws Exception {
        try (Statement st = con.createStatement()) {
            st.execute("CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR(100), identificacion VARCHAR(13), direccion VARCHAR(100), correo VARCHAR(60), telefono VARCHAR(10), celular VARCHAR(10), fecha_registro TIMESTAMP, estado BOOLEAN)");
        }
    }

    @Test
    void guardarYListar_cliente_sePersisteCorrectamente() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "")) {
            DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
            crearTabla(con);
            ClienteDAO dao = new ClienteDAO();
            Cliente c = new Cliente();
            c.setNombre("Juan Perez");
            c.setIdentificacion("1790000000001");
            c.setDireccion("Av. Principal");
            c.setCorreo("juan@example.com");
            c.setTelefono("0999999999");
            c.setCelular("0999999999");
            c.setEstado(true);
            dao.guardar(c);
            List<Cliente> lista = dao.listar();
            assertEquals(1, lista.size());
            assertEquals("Juan Perez", lista.get(0).getNombre());
        } finally {
            DatabaseConnection.resetToDefault();
        }
    }

    @Test
    void listar_sinClientes_retornaListaVacia() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "")) {
            DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
            crearTabla(con);
            ClienteDAO dao = new ClienteDAO();
            List<Cliente> lista = dao.listar();
            assertTrue(lista.isEmpty());
        } finally {
            DatabaseConnection.resetToDefault();
        }
    }

    @Test
    void guardarYActualizar_cliente_cambiosSePersisten() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "")) {
            DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
            crearTabla(con);
            ClienteDAO dao = new ClienteDAO();
            Cliente c = new Cliente();
            c.setNombre("Juan Perez");
            c.setIdentificacion("1790000000001");
            c.setDireccion("Av. Principal");
            c.setCorreo("juan@example.com");
            c.setTelefono("0999999999");
            c.setCelular("0999999999");
            c.setEstado(true);
            dao.guardar(c);
            List<Cliente> lista = dao.listar();
            Cliente guardado = lista.get(0);
            guardado.setNombre("Juan Perez Actualizado");
            dao.actualizar(guardado);
            List<Cliente> listaActualizada = dao.listar();
            assertEquals("Juan Perez Actualizado", listaActualizada.get(0).getNombre());
        } finally {
            DatabaseConnection.resetToDefault();
        }
    }

    @Test
    void guardarYEliminar_cliente_seEliminaCorrectamente() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "")) {
            DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
            crearTabla(con);
            ClienteDAO dao = new ClienteDAO();
            Cliente c = new Cliente();
            c.setNombre("Juan Perez");
            c.setIdentificacion("1790000000001");
            c.setDireccion("Av. Principal");
            c.setCorreo("juan@example.com");
            c.setTelefono("0999999999");
            c.setCelular("0999999999");
            c.setEstado(true);
            dao.guardar(c);
            List<Cliente> lista = dao.listar();
            assertEquals(1, lista.size());
            dao.eliminar(lista.get(0).getId());
            List<Cliente> listaVacia = dao.listar();
            assertTrue(listaVacia.isEmpty());
        } finally {
            DatabaseConnection.resetToDefault();
        }
    }
}
