package com.tag.sysTagRep.dao;

import com.tag.sysTagRep.config.DatabaseConnection;
import com.tag.sysTagRep.model.Proveedor;
import org.junit.jupiter.api.Test;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

class ProveedorDAOTest {

    private Connection getConnection() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        return DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "");
    }

    private void crearTabla(Connection con) throws Exception {
        try (Statement st = con.createStatement()) {
            st.execute("CREATE TABLE proveedor (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR(100), identificacion VARCHAR(13), direccion VARCHAR(100), correo VARCHAR(60), telefono VARCHAR(10), celular VARCHAR(10), fecha_registro TIMESTAMP, estado BOOLEAN)");
        }
    }

    @Test
    void guardarYListar_proveedor_sePersisteCorrectamente() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "")) {
            DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
            crearTabla(con);
            ProveedorDAO dao = new ProveedorDAO();
            Proveedor p = new Proveedor();
            p.setNombre("Bosch");
            p.setIdentificacion("1790000000001");
            p.setDireccion("Av. Industrial");
            p.setCorreo("bosch@example.com");
            p.setTelefono("0999999999");
            p.setCelular("0999999999");
            p.setEstado(true);
            dao.guardar(p);
            List<Proveedor> lista = dao.listar();
            assertEquals(1, lista.size());
            assertEquals("Bosch", lista.get(0).getNombre());
        } finally {
            DatabaseConnection.resetToDefault();
        }
    }

    @Test
    void listar_sinProveedores_retornaListaVacia() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "")) {
            DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
            crearTabla(con);
            ProveedorDAO dao = new ProveedorDAO();
            List<Proveedor> lista = dao.listar();
            assertTrue(lista.isEmpty());
        } finally {
            DatabaseConnection.resetToDefault();
        }
    }

    @Test
    void guardarYEliminar_proveedor_seEliminaCorrectamente() throws Exception {
        String dbName = "testdb_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection con = DriverManager.getConnection("jdbc:hsqldb:mem:" + dbName, "sa", "")) {
            DatabaseConnection.setConnectionParams("jdbc:hsqldb:mem:" + dbName, "sa", "");
            crearTabla(con);
            ProveedorDAO dao = new ProveedorDAO();
            Proveedor p = new Proveedor();
            p.setNombre("Bosch");
            p.setIdentificacion("1790000000001");
            p.setDireccion("Av. Industrial");
            p.setCorreo("bosch@example.com");
            p.setTelefono("0999999999");
            p.setCelular("0999999999");
            p.setEstado(true);
            dao.guardar(p);
            List<Proveedor> lista = dao.listar();
            assertEquals(1, lista.size());
            dao.eliminar(lista.get(0).getId());
            List<Proveedor> listaVacia = dao.listar();
            assertTrue(listaVacia.isEmpty());
        } finally {
            DatabaseConnection.resetToDefault();
        }
    }
}
