ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS permisos TEXT DEFAULT '';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS username VARCHAR(50) UNIQUE DEFAULT '';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS password VARCHAR(64) DEFAULT '';
