-- =====================================================================
-- faltantes_dbTag_prd.sql — Nivelar produccion (dbTag) con desarrollo (dbVendex)
-- Generado: comparar dbTag_prd (restaurado de BackupDbTag_10_6_26) vs dbVendex
--   24 tablas nuevas + 13 columnas en tablas existentes + 1 rename + 1 widen
-- USO (como postgres, con Vendex cerrado):
--   psql -h localhost -U postgres -d dbTag -v ON_ERROR_STOP=1 -f faltantes_dbTag_prd.sql
-- IDEMPOTENTE: re-ejecutable (IF NOT EXISTS + DO blocks).
-- SOLO ADITIVO: no hay DROP ni ALTER destructivos. No toca datos existentes.
-- =====================================================================

SET client_min_messages = WARNING;
BEGIN;


-- ---------- TABLA NUEVA: vehiculo ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: vehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.vehiculo (
    id integer NOT NULL,
    marca character varying(50) NOT NULL,
    modelo character varying(50) NOT NULL,
    anio_desde integer,
    anio_hasta integer,
    motor character varying(50),
    combustible character varying(20),
    vin_prefijo character varying(8),
    pais_origen character varying(50),
    tipo_vehiculo character varying(30),
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: vehiculo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid='public.vehiculo'::regclass AND attname='id' AND attidentity <> '') THEN
        ALTER TABLE public.vehiculo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.vehiculo_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END $$;


--
-- Name: vehiculo vehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'vehiculo_pkey' AND conrelid = 'public.vehiculo'::regclass) THEN
        ALTER TABLE ONLY public.vehiculo ADD CONSTRAINT vehiculo_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_vehiculo_anio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_vehiculo_anio ON public.vehiculo USING btree (anio_desde, anio_hasta);


--
-- Name: idx_vehiculo_marca_modelo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_vehiculo_marca_modelo ON public.vehiculo USING btree (marca, modelo);


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: rol ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.rol (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion character varying(200),
    limite_descuento_pct numeric(5,2) DEFAULT NULL::numeric
);


--
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.rol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rol_id_seq OWNED BY public.rol.id;


--
-- Name: rol id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol ALTER COLUMN id SET DEFAULT nextval('public.rol_id_seq'::regclass);


--
-- Name: rol rol_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'rol_nombre_key' AND conrelid = 'public.rol'::regclass) THEN
        ALTER TABLE ONLY public.rol ADD CONSTRAINT rol_nombre_key UNIQUE (nombre);
    END IF;
END $$;


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'rol_pkey' AND conrelid = 'public.rol'::regclass) THEN
        ALTER TABLE ONLY public.rol ADD CONSTRAINT rol_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: permiso ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: permiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.permiso (
    codigo character varying(50) NOT NULL,
    descripcion character varying(200) NOT NULL,
    categoria character varying(50) NOT NULL
);


--
-- Name: permiso permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'permiso_pkey' AND conrelid = 'public.permiso'::regclass) THEN
        ALTER TABLE ONLY public.permiso ADD CONSTRAINT permiso_pkey PRIMARY KEY (codigo);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: sucursal ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sucursal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.sucursal (
    id integer NOT NULL,
    codigo character varying(3) NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(300),
    telefono character varying(20),
    es_central boolean DEFAULT false NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    creado_en timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: sucursal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.sucursal_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sucursal_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sucursal_id_seq OWNED BY public.sucursal.id;


--
-- Name: sucursal id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sucursal ALTER COLUMN id SET DEFAULT nextval('public.sucursal_id_seq'::regclass);


--
-- Name: sucursal sucursal_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sucursal_codigo_key' AND conrelid = 'public.sucursal'::regclass) THEN
        ALTER TABLE ONLY public.sucursal ADD CONSTRAINT sucursal_codigo_key UNIQUE (codigo);
    END IF;
END $$;


--
-- Name: sucursal sucursal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sucursal_pkey' AND conrelid = 'public.sucursal'::regclass) THEN
        ALTER TABLE ONLY public.sucursal ADD CONSTRAINT sucursal_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: configuracion ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: configuracion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.configuracion (
    clave character varying(100) NOT NULL,
    valor text NOT NULL,
    descripcion character varying(300),
    actualizado_en timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: configuracion configuracion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'configuracion_pkey' AND conrelid = 'public.configuracion'::regclass) THEN
        ALTER TABLE ONLY public.configuracion ADD CONSTRAINT configuracion_pkey PRIMARY KEY (clave);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: certificado_estado ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: certificado_estado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.certificado_estado (
    id integer NOT NULL,
    ruta_p12 character varying(500) NOT NULL,
    titular character varying(300),
    fecha_emision date,
    fecha_expiracion date NOT NULL,
    dias_restantes integer NOT NULL,
    nivel_severidad character varying(15) NOT NULL,
    ultima_verificacion timestamp without time zone DEFAULT now() NOT NULL,
    ultimo_email_enviado timestamp without time zone
);


--
-- Name: certificado_estado_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.certificado_estado_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: certificado_estado_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.certificado_estado_id_seq OWNED BY public.certificado_estado.id;


--
-- Name: certificado_estado id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificado_estado ALTER COLUMN id SET DEFAULT nextval('public.certificado_estado_id_seq'::regclass);


--
-- Name: certificado_estado certificado_estado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'certificado_estado_pkey' AND conrelid = 'public.certificado_estado'::regclass) THEN
        ALTER TABLE ONLY public.certificado_estado ADD CONSTRAINT certificado_estado_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_certificado_ruta; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_certificado_ruta ON public.certificado_estado USING btree (ruta_p12);


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: login_intento_log ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: login_intento_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.login_intento_log (
    id integer NOT NULL,
    usuario_input character varying(150) NOT NULL,
    exitoso boolean NOT NULL,
    equipo character varying(150),
    creado_en timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: login_intento_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.login_intento_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: login_intento_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.login_intento_log_id_seq OWNED BY public.login_intento_log.id;


--
-- Name: login_intento_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.login_intento_log ALTER COLUMN id SET DEFAULT nextval('public.login_intento_log_id_seq'::regclass);


--
-- Name: login_intento_log login_intento_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'login_intento_log_pkey' AND conrelid = 'public.login_intento_log'::regclass) THEN
        ALTER TABLE ONLY public.login_intento_log ADD CONSTRAINT login_intento_log_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_login_log_creado_en; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_login_log_creado_en ON public.login_intento_log USING btree (creado_en);


--
-- Name: idx_login_log_usuario_input; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_login_log_usuario_input ON public.login_intento_log USING btree (usuario_input);


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: tabla_retencion ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tabla_retencion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tabla_retencion (
    id integer NOT NULL,
    codigo_retencion character varying(4) NOT NULL,
    descripcion character varying(200) NOT NULL,
    tipo character varying(1) NOT NULL,
    porcentaje numeric(5,2) NOT NULL,
    vigente_desde date NOT NULL,
    vigente_hasta date
);


--
-- Name: tabla_retencion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.tabla_retencion_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tabla_retencion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tabla_retencion_id_seq OWNED BY public.tabla_retencion.id;


--
-- Name: tabla_retencion id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tabla_retencion ALTER COLUMN id SET DEFAULT nextval('public.tabla_retencion_id_seq'::regclass);


--
-- Name: tabla_retencion tabla_retencion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tabla_retencion_pkey' AND conrelid = 'public.tabla_retencion'::regclass) THEN
        ALTER TABLE ONLY public.tabla_retencion ADD CONSTRAINT tabla_retencion_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_tabla_retencion_codigo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_tabla_retencion_codigo ON public.tabla_retencion USING btree (codigo_retencion);


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: acceso_directo ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acceso_directo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.acceso_directo (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    vista_ruta character varying(100) NOT NULL,
    titulo character varying(80) NOT NULL,
    icono_literal character varying(60) NOT NULL,
    posicion integer DEFAULT 0 NOT NULL,
    creado_en timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: acceso_directo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.acceso_directo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: acceso_directo_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.acceso_directo_id_seq OWNED BY public.acceso_directo.id;


--
-- Name: acceso_directo id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acceso_directo ALTER COLUMN id SET DEFAULT nextval('public.acceso_directo_id_seq'::regclass);


--
-- Name: acceso_directo acceso_directo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'acceso_directo_pkey' AND conrelid = 'public.acceso_directo'::regclass) THEN
        ALTER TABLE ONLY public.acceso_directo ADD CONSTRAINT acceso_directo_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: acceso_directo acceso_directo_usuario_id_vista_ruta_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'acceso_directo_usuario_id_vista_ruta_key' AND conrelid = 'public.acceso_directo'::regclass) THEN
        ALTER TABLE ONLY public.acceso_directo ADD CONSTRAINT acceso_directo_usuario_id_vista_ruta_key UNIQUE (usuario_id, vista_ruta);
    END IF;
END $$;


--
-- Name: idx_acceso_directo_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_acceso_directo_usuario ON public.acceso_directo USING btree (usuario_id);


--
-- Name: acceso_directo acceso_directo_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'acceso_directo_usuario_id_fkey' AND conrelid = 'public.acceso_directo'::regclass) THEN
        ALTER TABLE ONLY public.acceso_directo ADD CONSTRAINT acceso_directo_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: auditoria_accion ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auditoria_accion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.auditoria_accion (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    permiso_codigo character varying(50) NOT NULL,
    resultado character varying(15) NOT NULL,
    detalle character varying(300),
    creado_en timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: auditoria_accion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.auditoria_accion_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auditoria_accion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auditoria_accion_id_seq OWNED BY public.auditoria_accion.id;


--
-- Name: auditoria_accion id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_accion ALTER COLUMN id SET DEFAULT nextval('public.auditoria_accion_id_seq'::regclass);


--
-- Name: auditoria_accion auditoria_accion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'auditoria_accion_pkey' AND conrelid = 'public.auditoria_accion'::regclass) THEN
        ALTER TABLE ONLY public.auditoria_accion ADD CONSTRAINT auditoria_accion_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_auditoria_creado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_auditoria_creado ON public.auditoria_accion USING btree (creado_en);


--
-- Name: idx_auditoria_permiso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_auditoria_permiso ON public.auditoria_accion USING btree (permiso_codigo);


--
-- Name: idx_auditoria_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON public.auditoria_accion USING btree (usuario_id);


--
-- Name: auditoria_accion auditoria_accion_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'auditoria_accion_usuario_id_fkey' AND conrelid = 'public.auditoria_accion'::regclass) THEN
        ALTER TABLE ONLY public.auditoria_accion ADD CONSTRAINT auditoria_accion_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: comprobante_pendiente_sri ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comprobante_pendiente_sri; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.comprobante_pendiente_sri (
    id integer NOT NULL,
    comprobante_id integer,
    tipo_comprobante character varying(20) NOT NULL,
    clave_acceso character varying(49) NOT NULL,
    numero_comprobante character varying(30),
    ambiente character varying(10),
    intentos integer DEFAULT 0 NOT NULL,
    ultimo_intento timestamp without time zone,
    proximo_intento timestamp without time zone DEFAULT now() NOT NULL,
    estado character varying(15) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    ultimo_mensaje_sri character varying(500)
);


--
-- Name: comprobante_pendiente_sri_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.comprobante_pendiente_sri_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: comprobante_pendiente_sri_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.comprobante_pendiente_sri_id_seq OWNED BY public.comprobante_pendiente_sri.id;


--
-- Name: comprobante_pendiente_sri id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comprobante_pendiente_sri ALTER COLUMN id SET DEFAULT nextval('public.comprobante_pendiente_sri_id_seq'::regclass);


--
-- Name: comprobante_pendiente_sri comprobante_pendiente_sri_clave_acceso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comprobante_pendiente_sri_clave_acceso_key' AND conrelid = 'public.comprobante_pendiente_sri'::regclass) THEN
        ALTER TABLE ONLY public.comprobante_pendiente_sri ADD CONSTRAINT comprobante_pendiente_sri_clave_acceso_key UNIQUE (clave_acceso);
    END IF;
END $$;


--
-- Name: comprobante_pendiente_sri comprobante_pendiente_sri_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comprobante_pendiente_sri_pkey' AND conrelid = 'public.comprobante_pendiente_sri'::regclass) THEN
        ALTER TABLE ONLY public.comprobante_pendiente_sri ADD CONSTRAINT comprobante_pendiente_sri_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_pendiente_clave; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_pendiente_clave ON public.comprobante_pendiente_sri USING btree (clave_acceso);


--
-- Name: idx_pendiente_estado_proximo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_pendiente_estado_proximo ON public.comprobante_pendiente_sri USING btree (estado, proximo_intento);


--
-- Name: comprobante_pendiente_sri comprobante_pendiente_sri_comprobante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comprobante_pendiente_sri_comprobante_id_fkey' AND conrelid = 'public.comprobante_pendiente_sri'::regclass) THEN
        ALTER TABLE ONLY public.comprobante_pendiente_sri ADD CONSTRAINT comprobante_pendiente_sri_comprobante_id_fkey FOREIGN KEY (comprobante_id) REFERENCES public.comprobantes_electronicos(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: configuracion_email ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: configuracion_email; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.configuracion_email (
    id integer NOT NULL,
    host_smtp character varying(150) NOT NULL,
    puerto_smtp integer DEFAULT 587 NOT NULL,
    usar_tls boolean DEFAULT true NOT NULL,
    email_remitente character varying(150) NOT NULL,
    nombre_remitente character varying(150) NOT NULL,
    usuario_smtp character varying(150) NOT NULL,
    password_cifrado text NOT NULL,
    reply_to character varying(150),
    activo boolean DEFAULT true NOT NULL,
    actualizado_en timestamp without time zone DEFAULT now() NOT NULL,
    actualizado_por integer
);


--
-- Name: configuracion_email_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.configuracion_email_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: configuracion_email_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.configuracion_email_id_seq OWNED BY public.configuracion_email.id;


--
-- Name: configuracion_email id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_email ALTER COLUMN id SET DEFAULT nextval('public.configuracion_email_id_seq'::regclass);


--
-- Name: configuracion_email configuracion_email_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'configuracion_email_pkey' AND conrelid = 'public.configuracion_email'::regclass) THEN
        ALTER TABLE ONLY public.configuracion_email ADD CONSTRAINT configuracion_email_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_config_email_unica_activa; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX IF NOT EXISTS idx_config_email_unica_activa ON public.configuracion_email USING btree (activo) WHERE (activo = true);


--
-- Name: configuracion_email configuracion_email_actualizado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'configuracion_email_actualizado_por_fkey' AND conrelid = 'public.configuracion_email'::regclass) THEN
        ALTER TABLE ONLY public.configuracion_email ADD CONSTRAINT configuracion_email_actualizado_por_fkey FOREIGN KEY (actualizado_por) REFERENCES public.usuarios(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: guia_remision_registro ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: guia_remision_registro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.guia_remision_registro (
    id integer NOT NULL,
    clave_acceso character varying(49) NOT NULL,
    establecimiento character varying(3) DEFAULT '001'::character varying NOT NULL,
    punto_emision character varying(3) DEFAULT '001'::character varying NOT NULL,
    secuencial character varying(9) NOT NULL,
    fecha_emision timestamp without time zone DEFAULT now() NOT NULL,
    dir_partida character varying(300) NOT NULL,
    razon_social_transportista character varying(300) NOT NULL,
    tipo_identificacion_transportista character varying(2) CONSTRAINT guia_remision_registro_tipo_identificacion_transportis_not_null NOT NULL,
    ruc_transportista character varying(13) NOT NULL,
    placa character varying(10) NOT NULL,
    fecha_ini_transporte date NOT NULL,
    fecha_fin_transporte date NOT NULL,
    estado_sri character varying(15) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    mensaje_sri character varying(500),
    numero_autorizacion character varying(49),
    fecha_autorizacion timestamp without time zone,
    xml_firmado text,
    usuario_id integer NOT NULL,
    creado_en timestamp without time zone DEFAULT now() NOT NULL,
    sucursal_id integer DEFAULT 1
);


--
-- Name: guia_remision_registro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.guia_remision_registro_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: guia_remision_registro_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.guia_remision_registro_id_seq OWNED BY public.guia_remision_registro.id;


--
-- Name: guia_remision_registro id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guia_remision_registro ALTER COLUMN id SET DEFAULT nextval('public.guia_remision_registro_id_seq'::regclass);


--
-- Name: guia_remision_registro guia_remision_registro_clave_acceso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_registro_clave_acceso_key' AND conrelid = 'public.guia_remision_registro'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_registro ADD CONSTRAINT guia_remision_registro_clave_acceso_key UNIQUE (clave_acceso);
    END IF;
END $$;


--
-- Name: guia_remision_registro guia_remision_registro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_registro_pkey' AND conrelid = 'public.guia_remision_registro'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_registro ADD CONSTRAINT guia_remision_registro_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_guia_remision_clave; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_guia_remision_clave ON public.guia_remision_registro USING btree (clave_acceso);


--
-- Name: idx_guia_remision_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_guia_remision_estado ON public.guia_remision_registro USING btree (estado_sri);


--
-- Name: guia_remision_registro guia_remision_registro_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_registro_usuario_id_fkey' AND conrelid = 'public.guia_remision_registro'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_registro ADD CONSTRAINT guia_remision_registro_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: nota_credito_registro ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: nota_credito_registro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.nota_credito_registro (
    id integer NOT NULL,
    clave_acceso character varying(49) NOT NULL,
    factura_registro_id integer NOT NULL,
    establecimiento character varying(3) DEFAULT '001'::character varying NOT NULL,
    punto_emision character varying(3) DEFAULT '001'::character varying NOT NULL,
    secuencial character varying(9) NOT NULL,
    fecha_emision timestamp without time zone DEFAULT now() NOT NULL,
    cliente_id integer NOT NULL,
    motivo character varying(300) NOT NULL,
    tipo_motivo character varying(20) NOT NULL,
    total_sin_impuestos numeric(12,2) NOT NULL,
    valor_iva numeric(12,2) NOT NULL,
    valor_modificacion numeric(12,2) NOT NULL,
    reingresa_stock boolean DEFAULT false NOT NULL,
    estado_sri character varying(15) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    mensaje_sri character varying(500),
    numero_autorizacion character varying(49),
    fecha_autorizacion timestamp without time zone,
    xml_firmado text,
    usuario_id integer NOT NULL,
    creado_en timestamp without time zone DEFAULT now() NOT NULL,
    sucursal_id integer DEFAULT 1,
    CONSTRAINT nota_credito_registro_tipo_motivo_check CHECK (((tipo_motivo)::text = ANY ((ARRAY['DEVOLUCION'::character varying, 'DESCUENTO'::character varying, 'ANULACION'::character varying])::text[])))
);


--
-- Name: nota_credito_registro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.nota_credito_registro_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: nota_credito_registro_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nota_credito_registro_id_seq OWNED BY public.nota_credito_registro.id;


--
-- Name: nota_credito_registro id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_credito_registro ALTER COLUMN id SET DEFAULT nextval('public.nota_credito_registro_id_seq'::regclass);


--
-- Name: nota_credito_registro nota_credito_registro_clave_acceso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_registro_clave_acceso_key' AND conrelid = 'public.nota_credito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_registro ADD CONSTRAINT nota_credito_registro_clave_acceso_key UNIQUE (clave_acceso);
    END IF;
END $$;


--
-- Name: nota_credito_registro nota_credito_registro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_registro_pkey' AND conrelid = 'public.nota_credito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_registro ADD CONSTRAINT nota_credito_registro_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_nota_credito_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_nota_credito_estado ON public.nota_credito_registro USING btree (estado_sri);


--
-- Name: idx_nota_credito_factura; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_nota_credito_factura ON public.nota_credito_registro USING btree (factura_registro_id);


--
-- Name: nota_credito_registro nota_credito_registro_cliente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_registro_cliente_id_fkey' AND conrelid = 'public.nota_credito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_registro ADD CONSTRAINT nota_credito_registro_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
    END IF;
END $$;


--
-- Name: nota_credito_registro nota_credito_registro_factura_registro_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_registro_factura_registro_id_fkey' AND conrelid = 'public.nota_credito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_registro ADD CONSTRAINT nota_credito_registro_factura_registro_id_fkey FOREIGN KEY (factura_registro_id) REFERENCES public.factura_registro(id);
    END IF;
END $$;


--
-- Name: nota_credito_registro nota_credito_registro_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_registro_usuario_id_fkey' AND conrelid = 'public.nota_credito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_registro ADD CONSTRAINT nota_credito_registro_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: nota_debito_registro ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: nota_debito_registro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.nota_debito_registro (
    id integer NOT NULL,
    clave_acceso character varying(49) NOT NULL,
    factura_registro_id integer NOT NULL,
    establecimiento character varying(3) DEFAULT '001'::character varying NOT NULL,
    punto_emision character varying(3) DEFAULT '001'::character varying NOT NULL,
    secuencial character varying(9) NOT NULL,
    fecha_emision timestamp without time zone DEFAULT now() NOT NULL,
    cliente_id integer NOT NULL,
    forma_pago character varying(2) NOT NULL,
    total_sin_impuestos numeric(12,2) NOT NULL,
    valor_iva numeric(12,2) DEFAULT 0 NOT NULL,
    valor_total numeric(12,2) NOT NULL,
    estado_sri character varying(15) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    mensaje_sri character varying(500),
    numero_autorizacion character varying(49),
    fecha_autorizacion timestamp without time zone,
    xml_firmado text,
    usuario_id integer NOT NULL,
    creado_en timestamp without time zone DEFAULT now() NOT NULL,
    sucursal_id integer DEFAULT 1
);


--
-- Name: nota_debito_registro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.nota_debito_registro_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: nota_debito_registro_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nota_debito_registro_id_seq OWNED BY public.nota_debito_registro.id;


--
-- Name: nota_debito_registro id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_debito_registro ALTER COLUMN id SET DEFAULT nextval('public.nota_debito_registro_id_seq'::regclass);


--
-- Name: nota_debito_registro nota_debito_registro_clave_acceso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_debito_registro_clave_acceso_key' AND conrelid = 'public.nota_debito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_debito_registro ADD CONSTRAINT nota_debito_registro_clave_acceso_key UNIQUE (clave_acceso);
    END IF;
END $$;


--
-- Name: nota_debito_registro nota_debito_registro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_debito_registro_pkey' AND conrelid = 'public.nota_debito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_debito_registro ADD CONSTRAINT nota_debito_registro_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_nota_debito_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_nota_debito_estado ON public.nota_debito_registro USING btree (estado_sri);


--
-- Name: idx_nota_debito_factura; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_nota_debito_factura ON public.nota_debito_registro USING btree (factura_registro_id);


--
-- Name: nota_debito_registro nota_debito_registro_cliente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_debito_registro_cliente_id_fkey' AND conrelid = 'public.nota_debito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_debito_registro ADD CONSTRAINT nota_debito_registro_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
    END IF;
END $$;


--
-- Name: nota_debito_registro nota_debito_registro_factura_registro_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_debito_registro_factura_registro_id_fkey' AND conrelid = 'public.nota_debito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_debito_registro ADD CONSTRAINT nota_debito_registro_factura_registro_id_fkey FOREIGN KEY (factura_registro_id) REFERENCES public.factura_registro(id);
    END IF;
END $$;


--
-- Name: nota_debito_registro nota_debito_registro_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_debito_registro_usuario_id_fkey' AND conrelid = 'public.nota_debito_registro'::regclass) THEN
        ALTER TABLE ONLY public.nota_debito_registro ADD CONSTRAINT nota_debito_registro_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: retencion_registro ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: retencion_registro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.retencion_registro (
    id integer NOT NULL,
    clave_acceso character varying(49) NOT NULL,
    establecimiento character varying(3) DEFAULT '001'::character varying NOT NULL,
    punto_emision character varying(3) DEFAULT '001'::character varying NOT NULL,
    secuencial character varying(9) NOT NULL,
    fecha_emision timestamp without time zone DEFAULT now() NOT NULL,
    periodo_fiscal character varying(7) NOT NULL,
    proveedor_id integer,
    tipo_identificacion_sujeto character varying(2) NOT NULL,
    razon_social_sujeto character varying(300) NOT NULL,
    identificacion_sujeto character varying(13) NOT NULL,
    estado_sri character varying(15) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    mensaje_sri character varying(500),
    numero_autorizacion character varying(49),
    fecha_autorizacion timestamp without time zone,
    xml_firmado text,
    usuario_id integer NOT NULL,
    creado_en timestamp without time zone DEFAULT now() NOT NULL,
    sucursal_id integer DEFAULT 1
);


--
-- Name: retencion_registro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.retencion_registro_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: retencion_registro_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.retencion_registro_id_seq OWNED BY public.retencion_registro.id;


--
-- Name: retencion_registro id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retencion_registro ALTER COLUMN id SET DEFAULT nextval('public.retencion_registro_id_seq'::regclass);


--
-- Name: retencion_registro retencion_registro_clave_acceso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_registro_clave_acceso_key' AND conrelid = 'public.retencion_registro'::regclass) THEN
        ALTER TABLE ONLY public.retencion_registro ADD CONSTRAINT retencion_registro_clave_acceso_key UNIQUE (clave_acceso);
    END IF;
END $$;


--
-- Name: retencion_registro retencion_registro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_registro_pkey' AND conrelid = 'public.retencion_registro'::regclass) THEN
        ALTER TABLE ONLY public.retencion_registro ADD CONSTRAINT retencion_registro_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_retencion_clave; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_retencion_clave ON public.retencion_registro USING btree (clave_acceso);


--
-- Name: idx_retencion_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_retencion_estado ON public.retencion_registro USING btree (estado_sri);


--
-- Name: retencion_registro retencion_registro_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_registro_proveedor_id_fkey' AND conrelid = 'public.retencion_registro'::regclass) THEN
        ALTER TABLE ONLY public.retencion_registro ADD CONSTRAINT retencion_registro_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedor(id);
    END IF;
END $$;


--
-- Name: retencion_registro retencion_registro_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_registro_usuario_id_fkey' AND conrelid = 'public.retencion_registro'::regclass) THEN
        ALTER TABLE ONLY public.retencion_registro ADD CONSTRAINT retencion_registro_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: inventario_vehiculo ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: inventario_vehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.inventario_vehiculo (
    inventario_id integer NOT NULL,
    vehiculo_id integer NOT NULL,
    notas character varying(200)
);


--
-- Name: inventario_vehiculo inventario_vehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inventario_vehiculo_pkey' AND conrelid = 'public.inventario_vehiculo'::regclass) THEN
        ALTER TABLE ONLY public.inventario_vehiculo ADD CONSTRAINT inventario_vehiculo_pkey PRIMARY KEY (inventario_id, vehiculo_id);
    END IF;
END $$;


--
-- Name: idx_iv_veh_inventario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_iv_veh_inventario ON public.inventario_vehiculo USING btree (inventario_id);


--
-- Name: idx_iv_veh_vehiculo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_iv_veh_vehiculo ON public.inventario_vehiculo USING btree (vehiculo_id);


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: nota_credito_detalle ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: nota_credito_detalle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.nota_credito_detalle (
    id integer NOT NULL,
    nota_credito_id integer NOT NULL,
    factura_detalle_id integer,
    inventario_id integer,
    descripcion character varying(300) NOT NULL,
    cantidad numeric(10,2) NOT NULL,
    precio_unitario numeric(12,4) NOT NULL,
    descuento numeric(12,2) DEFAULT 0 NOT NULL,
    codigo_porcentaje_iva character varying(2) DEFAULT '4'::character varying NOT NULL,
    precio_total_sin_impuesto numeric(12,2) NOT NULL
);


--
-- Name: nota_credito_detalle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.nota_credito_detalle_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: nota_credito_detalle_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nota_credito_detalle_id_seq OWNED BY public.nota_credito_detalle.id;


--
-- Name: nota_credito_detalle id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_credito_detalle ALTER COLUMN id SET DEFAULT nextval('public.nota_credito_detalle_id_seq'::regclass);


--
-- Name: nota_credito_detalle nota_credito_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_detalle_pkey' AND conrelid = 'public.nota_credito_detalle'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_detalle ADD CONSTRAINT nota_credito_detalle_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_nota_credito_detalle_nc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_nota_credito_detalle_nc ON public.nota_credito_detalle USING btree (nota_credito_id);


--
-- Name: nota_credito_detalle nota_credito_detalle_factura_detalle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_detalle_factura_detalle_id_fkey' AND conrelid = 'public.nota_credito_detalle'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_detalle ADD CONSTRAINT nota_credito_detalle_factura_detalle_id_fkey FOREIGN KEY (factura_detalle_id) REFERENCES public.factura_detalle(id);
    END IF;
END $$;


--
-- Name: nota_credito_detalle nota_credito_detalle_inventario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_detalle_inventario_id_fkey' AND conrelid = 'public.nota_credito_detalle'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_detalle ADD CONSTRAINT nota_credito_detalle_inventario_id_fkey FOREIGN KEY (inventario_id) REFERENCES public.inventario(id);
    END IF;
END $$;


--
-- Name: nota_credito_detalle nota_credito_detalle_nota_credito_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_credito_detalle_nota_credito_id_fkey' AND conrelid = 'public.nota_credito_detalle'::regclass) THEN
        ALTER TABLE ONLY public.nota_credito_detalle ADD CONSTRAINT nota_credito_detalle_nota_credito_id_fkey FOREIGN KEY (nota_credito_id) REFERENCES public.nota_credito_registro(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: nota_debito_motivo ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: nota_debito_motivo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.nota_debito_motivo (
    id integer NOT NULL,
    nota_debito_id integer NOT NULL,
    razon character varying(300) NOT NULL,
    valor numeric(12,2) NOT NULL,
    grava_iva boolean DEFAULT true NOT NULL,
    codigo_porcentaje_iva character varying(2) DEFAULT '4'::character varying NOT NULL
);


--
-- Name: nota_debito_motivo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.nota_debito_motivo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: nota_debito_motivo_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nota_debito_motivo_id_seq OWNED BY public.nota_debito_motivo.id;


--
-- Name: nota_debito_motivo id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_debito_motivo ALTER COLUMN id SET DEFAULT nextval('public.nota_debito_motivo_id_seq'::regclass);


--
-- Name: nota_debito_motivo nota_debito_motivo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_debito_motivo_pkey' AND conrelid = 'public.nota_debito_motivo'::regclass) THEN
        ALTER TABLE ONLY public.nota_debito_motivo ADD CONSTRAINT nota_debito_motivo_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_nota_debito_motivo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_nota_debito_motivo ON public.nota_debito_motivo USING btree (nota_debito_id);


--
-- Name: nota_debito_motivo nota_debito_motivo_nota_debito_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nota_debito_motivo_nota_debito_id_fkey' AND conrelid = 'public.nota_debito_motivo'::regclass) THEN
        ALTER TABLE ONLY public.nota_debito_motivo ADD CONSTRAINT nota_debito_motivo_nota_debito_id_fkey FOREIGN KEY (nota_debito_id) REFERENCES public.nota_debito_registro(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: retencion_documento_sustento ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: retencion_documento_sustento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.retencion_documento_sustento (
    id integer NOT NULL,
    retencion_id integer NOT NULL,
    cod_sustento character varying(2) DEFAULT '01'::character varying NOT NULL,
    cod_doc_sustento character varying(2) DEFAULT '01'::character varying NOT NULL,
    num_doc_sustento character varying(17) NOT NULL,
    fecha_emision_doc_sustento date CONSTRAINT retencion_documento_sustent_fecha_emision_doc_sustento_not_null NOT NULL,
    total_sin_impuestos numeric(12,2) NOT NULL
);


--
-- Name: retencion_documento_sustento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.retencion_documento_sustento_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: retencion_documento_sustento_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.retencion_documento_sustento_id_seq OWNED BY public.retencion_documento_sustento.id;


--
-- Name: retencion_documento_sustento id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retencion_documento_sustento ALTER COLUMN id SET DEFAULT nextval('public.retencion_documento_sustento_id_seq'::regclass);


--
-- Name: retencion_documento_sustento retencion_documento_sustento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_documento_sustento_pkey' AND conrelid = 'public.retencion_documento_sustento'::regclass) THEN
        ALTER TABLE ONLY public.retencion_documento_sustento ADD CONSTRAINT retencion_documento_sustento_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_retencion_doc_retencion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_retencion_doc_retencion ON public.retencion_documento_sustento USING btree (retencion_id);


--
-- Name: retencion_documento_sustento retencion_documento_sustento_retencion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_documento_sustento_retencion_id_fkey' AND conrelid = 'public.retencion_documento_sustento'::regclass) THEN
        ALTER TABLE ONLY public.retencion_documento_sustento ADD CONSTRAINT retencion_documento_sustento_retencion_id_fkey FOREIGN KEY (retencion_id) REFERENCES public.retencion_registro(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: rol_permiso ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: rol_permiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.rol_permiso (
    rol_id integer NOT NULL,
    permiso_codigo character varying(50) NOT NULL
);


--
-- Name: rol_permiso rol_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'rol_permiso_pkey' AND conrelid = 'public.rol_permiso'::regclass) THEN
        ALTER TABLE ONLY public.rol_permiso ADD CONSTRAINT rol_permiso_pkey PRIMARY KEY (rol_id, permiso_codigo);
    END IF;
END $$;


--
-- Name: rol_permiso rol_permiso_permiso_codigo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'rol_permiso_permiso_codigo_fkey' AND conrelid = 'public.rol_permiso'::regclass) THEN
        ALTER TABLE ONLY public.rol_permiso ADD CONSTRAINT rol_permiso_permiso_codigo_fkey FOREIGN KEY (permiso_codigo) REFERENCES public.permiso(codigo) ON DELETE CASCADE;
    END IF;
END $$;


--
-- Name: rol_permiso rol_permiso_rol_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'rol_permiso_rol_id_fkey' AND conrelid = 'public.rol_permiso'::regclass) THEN
        ALTER TABLE ONLY public.rol_permiso ADD CONSTRAINT rol_permiso_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.rol(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: guia_remision_destinatario ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: guia_remision_destinatario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.guia_remision_destinatario (
    id integer NOT NULL,
    guia_remision_id integer NOT NULL,
    identificacion_destinatario character varying(20) NOT NULL,
    razon_social_destinatario character varying(300) NOT NULL,
    direccion_destinatario character varying(300) NOT NULL,
    motivo_traslado character varying(300) NOT NULL,
    factura_registro_id integer,
    cod_doc_sustento character varying(2),
    num_doc_sustento character varying(17),
    num_aut_doc_sustento character varying(49),
    fecha_emision_doc_sustento date
);


--
-- Name: guia_remision_destinatario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.guia_remision_destinatario_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: guia_remision_destinatario_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.guia_remision_destinatario_id_seq OWNED BY public.guia_remision_destinatario.id;


--
-- Name: guia_remision_destinatario id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guia_remision_destinatario ALTER COLUMN id SET DEFAULT nextval('public.guia_remision_destinatario_id_seq'::regclass);


--
-- Name: guia_remision_destinatario guia_remision_destinatario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_destinatario_pkey' AND conrelid = 'public.guia_remision_destinatario'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_destinatario ADD CONSTRAINT guia_remision_destinatario_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_guia_destinatario_guia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_guia_destinatario_guia ON public.guia_remision_destinatario USING btree (guia_remision_id);


--
-- Name: guia_remision_destinatario guia_remision_destinatario_factura_registro_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_destinatario_factura_registro_id_fkey' AND conrelid = 'public.guia_remision_destinatario'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_destinatario ADD CONSTRAINT guia_remision_destinatario_factura_registro_id_fkey FOREIGN KEY (factura_registro_id) REFERENCES public.factura_registro(id);
    END IF;
END $$;


--
-- Name: guia_remision_destinatario guia_remision_destinatario_guia_remision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_destinatario_guia_remision_id_fkey' AND conrelid = 'public.guia_remision_destinatario'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_destinatario ADD CONSTRAINT guia_remision_destinatario_guia_remision_id_fkey FOREIGN KEY (guia_remision_id) REFERENCES public.guia_remision_registro(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: retencion_detalle ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: retencion_detalle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.retencion_detalle (
    id integer NOT NULL,
    doc_sustento_id integer NOT NULL,
    codigo character varying(1) NOT NULL,
    codigo_retencion character varying(4) NOT NULL,
    base_imponible numeric(12,2) NOT NULL,
    porcentaje_retener numeric(5,2) NOT NULL,
    valor_retenido numeric(12,2) NOT NULL
);


--
-- Name: retencion_detalle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.retencion_detalle_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: retencion_detalle_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.retencion_detalle_id_seq OWNED BY public.retencion_detalle.id;


--
-- Name: retencion_detalle id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retencion_detalle ALTER COLUMN id SET DEFAULT nextval('public.retencion_detalle_id_seq'::regclass);


--
-- Name: retencion_detalle retencion_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_detalle_pkey' AND conrelid = 'public.retencion_detalle'::regclass) THEN
        ALTER TABLE ONLY public.retencion_detalle ADD CONSTRAINT retencion_detalle_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_retencion_det_doc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_retencion_det_doc ON public.retencion_detalle USING btree (doc_sustento_id);


--
-- Name: retencion_detalle retencion_detalle_doc_sustento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retencion_detalle_doc_sustento_id_fkey' AND conrelid = 'public.retencion_detalle'::regclass) THEN
        ALTER TABLE ONLY public.retencion_detalle ADD CONSTRAINT retencion_detalle_doc_sustento_id_fkey FOREIGN KEY (doc_sustento_id) REFERENCES public.retencion_documento_sustento(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- TABLA NUEVA: guia_remision_detalle ----------
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: guia_remision_detalle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.guia_remision_detalle (
    id integer NOT NULL,
    guia_remision_destinatario_id integer NOT NULL,
    inventario_id integer,
    codigo_interno character varying(25) NOT NULL,
    descripcion character varying(300) NOT NULL,
    cantidad numeric(10,2) NOT NULL
);


--
-- Name: guia_remision_detalle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE IF NOT EXISTS public.guia_remision_detalle_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: guia_remision_detalle_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.guia_remision_detalle_id_seq OWNED BY public.guia_remision_detalle.id;


--
-- Name: guia_remision_detalle id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guia_remision_detalle ALTER COLUMN id SET DEFAULT nextval('public.guia_remision_detalle_id_seq'::regclass);


--
-- Name: guia_remision_detalle guia_remision_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_detalle_pkey' AND conrelid = 'public.guia_remision_detalle'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_detalle ADD CONSTRAINT guia_remision_detalle_pkey PRIMARY KEY (id);
    END IF;
END $$;


--
-- Name: idx_guia_detalle_dest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_guia_detalle_dest ON public.guia_remision_detalle USING btree (guia_remision_destinatario_id);


--
-- Name: guia_remision_detalle guia_remision_detalle_guia_remision_destinatario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_detalle_guia_remision_destinatario_id_fkey' AND conrelid = 'public.guia_remision_detalle'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_detalle ADD CONSTRAINT guia_remision_detalle_guia_remision_destinatario_id_fkey FOREIGN KEY (guia_remision_destinatario_id) REFERENCES public.guia_remision_destinatario(id) ON DELETE CASCADE;
    END IF;
END $$;


--
-- Name: guia_remision_detalle guia_remision_detalle_inventario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'guia_remision_detalle_inventario_id_fkey' AND conrelid = 'public.guia_remision_detalle'::regclass) THEN
        ALTER TABLE ONLY public.guia_remision_detalle ADD CONSTRAINT guia_remision_detalle_inventario_id_fkey FOREIGN KEY (inventario_id) REFERENCES public.inventario(id);
    END IF;
END $$;


--
-- PostgreSQL database dump complete
--



-- ---------- COLUMNAS FALTANTES EN TABLAS EXISTENTES ----------
ALTER TABLE public.caja_sesion      ADD COLUMN IF NOT EXISTS sucursal_id integer NOT NULL DEFAULT 1;
ALTER TABLE public.factura_registro ADD COLUMN IF NOT EXISTS estado_gr  character varying(20) NOT NULL DEFAULT 'NINGUNA';
ALTER TABLE public.factura_registro ADD COLUMN IF NOT EXISTS estado_nc  character varying(20) NOT NULL DEFAULT 'NINGUNA';
ALTER TABLE public.factura_registro ADD COLUMN IF NOT EXISTS estado_nd  character varying(20) NOT NULL DEFAULT 'NINGUNA';
ALTER TABLE public.factura_registro ADD COLUMN IF NOT EXISTS sucursal_id integer NOT NULL DEFAULT 1;
ALTER TABLE public.inventario       ADD COLUMN IF NOT EXISTS sucursal_id integer NOT NULL DEFAULT 1;
ALTER TABLE public.nota_venta_registro ADD COLUMN IF NOT EXISTS sucursal_id integer NOT NULL DEFAULT 1;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS bloqueado_hasta timestamp without time zone;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS intentos_fallidos integer NOT NULL DEFAULT 0;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS limite_descuento_pct numeric(5,2);
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS rol_id integer;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS ultimo_intento_fallido timestamp without time zone;
-- FK usuarios.rol_id -> rol.id (solo si no existe; NULLs existentes siempre validan)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'usuarios_rol_id_fkey') THEN
        ALTER TABLE public.usuarios ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES rol(id);
    END IF;
END $$;

-- ---------- RENAME: comprobantes_electronicos.nota_venta_id -> documento_relacionado_id ----------
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema='public' AND table_name='comprobantes_electronicos' AND column_name='nota_venta_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema='public' AND table_name='comprobantes_electronicos' AND column_name='documento_relacionado_id') THEN
        ALTER TABLE public.comprobantes_electronicos RENAME COLUMN nota_venta_id TO documento_relacionado_id;
    END IF;
END $$;

-- ---------- WIDEN: comprobantes_electronicos.numero_comprobante VARCHAR(15)->(30) ----------
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema='public' AND table_name='comprobantes_electronicos'
               AND column_name='numero_comprobante' AND character_maximum_length < 30) THEN
        ALTER TABLE public.comprobantes_electronicos ALTER COLUMN numero_comprobante TYPE VARCHAR(30);
    END IF;
END $$;


-- ---------- SEEDS (idempotentes; igual que ensure* del arranque) ----------
INSERT INTO sucursal(codigo, nombre, direccion, es_central, activo)
VALUES ('001', 'Matriz', 'Matriz', true, true) ON CONFLICT (codigo) DO NOTHING;

INSERT INTO configuracion (clave, valor, descripcion) VALUES
 ('bloqueo.intentos_permitidos','5','Intentos fallidos antes de bloquear'),
 ('bloqueo.ventana_minutos','15','Ventana reseteo contador'),
 ('bloqueo.duracion_minutos','15','Duracion inicial bloqueo backoff'),
 ('bloqueo.max_horas','24','Tope max bloqueo')
ON CONFLICT (clave) DO NOTHING;

INSERT INTO rol (nombre, descripcion, limite_descuento_pct) VALUES
 ('ADMINISTRADOR','Acceso total', NULL),
 ('VENDEDOR','Ventas y facturación', 5.00),
 ('CAJERO','Caja y cobranza', 0.00),
 ('BODEGUERO','Inventario y bodega', 0.00)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO permiso (codigo, descripcion, categoria) VALUES
 ('FACTURA_EMITIR','Emitir una factura nueva','FACTURACION'),
 ('FACTURA_ANULAR','Iniciar NC por anulación total','FACTURACION'),
 ('NOTA_CREDITO_EMITIR','Emitir NC','FACTURACION'),
 ('NOTA_DEBITO_EMITIR','Emitir ND','FACTURACION'),
 ('GUIA_REMISION_EMITIR','Emitir GR','FACTURACION'),
 ('RETENCION_EMITIR','Emitir retención','FACTURACION'),
 ('PRECIO_EDITAR','Modificar precio','INVENTARIO'),
 ('INVENTARIO_AJUSTAR','Ajuste manual de stock','INVENTARIO'),
 ('DESCUENTO_APLICAR','Aplicar descuentos','FACTURACION'),
 ('CAJA_ABRIR','Abrir caja','CAJA'),
 ('CAJA_CERRAR','Cerrar caja','CAJA'),
 ('CAJA_VER_HISTORICO','Ver cierres de caja','CAJA'),
 ('USUARIO_GESTIONAR','Gestionar usuarios y roles','USUARIOS'),
 ('CONFIGURACION_EMAIL_EDITAR','Editar correo','CONFIGURACION'),
 ('CONFIGURACION_BD_VER','Ver/editar conexión BD','CONFIGURACION'),
 ('REPORTE_VER','Ver dashboard y reportes','REPORTES'),
 ('REPORTE_VER_FINANCIERO','Ver reportes financieros','REPORTES')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO rol_permiso (rol_id, permiso_codigo)
SELECT r.id, p.codigo FROM rol r CROSS JOIN permiso p WHERE r.nombre='ADMINISTRADOR'
ON CONFLICT DO NOTHING;
INSERT INTO rol_permiso (rol_id, permiso_codigo)
SELECT r.id, x.cod FROM rol r CROSS JOIN (VALUES
 ('FACTURA_EMITIR'),('GUIA_REMISION_EMITIR'),('DESCUENTO_APLICAR'),('REPORTE_VER')) AS x(cod)
WHERE r.nombre='VENDEDOR' ON CONFLICT DO NOTHING;
INSERT INTO rol_permiso (rol_id, permiso_codigo)
SELECT r.id, x.cod FROM rol r CROSS JOIN (VALUES
 ('FACTURA_EMITIR'),('NOTA_CREDITO_EMITIR'),('CAJA_ABRIR'),('CAJA_CERRAR'),('REPORTE_VER')) AS x(cod)
WHERE r.nombre='CAJERO' ON CONFLICT DO NOTHING;
INSERT INTO rol_permiso (rol_id, permiso_codigo)
SELECT r.id, x.cod FROM rol r CROSS JOIN (VALUES
 ('GUIA_REMISION_EMITIR'),('INVENTARIO_AJUSTAR')) AS x(cod)
WHERE r.nombre='BODEGUERO' ON CONFLICT DO NOTHING;

INSERT INTO tabla_retencion (codigo_retencion, descripcion, tipo, porcentaje, vigente_desde)
SELECT '303','Honorarios profesionales','1',10.00,'2026-03-01' WHERE NOT EXISTS (SELECT 1 FROM tabla_retencion WHERE codigo_retencion='303' AND vigente_desde='2026-03-01');
INSERT INTO tabla_retencion (codigo_retencion, descripcion, tipo, porcentaje, vigente_desde)
SELECT '312','Transporte privado pasajeros','1',1.00,'2026-03-01' WHERE NOT EXISTS (SELECT 1 FROM tabla_retencion WHERE codigo_retencion='312' AND vigente_desde='2026-03-01');
INSERT INTO tabla_retencion (codigo_retencion, descripcion, tipo, porcentaje, vigente_desde)
SELECT '725','IVA bienes','2',30.00,'2026-03-01' WHERE NOT EXISTS (SELECT 1 FROM tabla_retencion WHERE codigo_retencion='725' AND vigente_desde='2026-03-01');
INSERT INTO tabla_retencion (codigo_retencion, descripcion, tipo, porcentaje, vigente_desde)
SELECT '723','IVA servicios','2',70.00,'2026-03-01' WHERE NOT EXISTS (SELECT 1 FROM tabla_retencion WHERE codigo_retencion='723' AND vigente_desde='2026-03-01');
INSERT INTO tabla_retencion (codigo_retencion, descripcion, tipo, porcentaje, vigente_desde)
SELECT '322','Seguros y reaseguros','1',1.75,'2026-03-01' WHERE NOT EXISTS (SELECT 1 FROM tabla_retencion WHERE codigo_retencion='322' AND vigente_desde='2026-03-01');

INSERT INTO vehiculo(marca, modelo, anio_desde, anio_hasta, motor, combustible, vin_prefijo, tipo_vehiculo)
SELECT 'CHEVROLET','AVEO',2012,2017,'1.6','Gasolina','3G1','Sedán'
WHERE NOT EXISTS (SELECT 1 FROM vehiculo WHERE marca='CHEVROLET' AND modelo='AVEO');
INSERT INTO vehiculo(marca, modelo, anio_desde, anio_hasta, motor, combustible, vin_prefijo, tipo_vehiculo)
SELECT 'TOYOTA','HILUX',2015,2024,'2.8','Diésel','8AJ','Pickup'
WHERE NOT EXISTS (SELECT 1 FROM vehiculo WHERE marca='TOYOTA' AND modelo='HILUX');


-- ---------- GRANTS app_vendex (se omiten si el rol no existe en prod) ----------
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_vendex') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_vendex;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_vendex;
    ELSE
        RAISE NOTICE 'Rol app_vendex no existe en esta BD: grants omitidos (la app corre como postgres).';
    END IF;
END $$;

COMMIT;
-- Verificacion sugerida tras aplicar:
--   SELECT count(*) FROM information_schema.tables WHERE table_schema='public';  -- esperado: 53

-- =====================================================================
-- SUPLEMENTO V32 — cuentas_por_cobrar.factura_registro_id (bug FK factura a credito)
-- Bug: FacturaService guardaba facturaId en nota_venta_id (FK a nota_venta_registro).
-- Secuencias independientes => "violates foreign key cuentas_por_cobrar_nota_venta_id_fkey".
-- Fix: columna factura_registro_id NULL con FK propia. Proformas usan nota_venta_id,
-- facturas usan factura_registro_id con nota_venta_id NULL. Idempotente.
-- =====================================================================

BEGIN;

ALTER TABLE public.cuentas_por_cobrar ADD COLUMN IF NOT EXISTS factura_registro_id INTEGER REFERENCES public.factura_registro(id);
CREATE INDEX IF NOT EXISTS idx_cpc_factura_registro ON public.cuentas_por_cobrar(factura_registro_id);

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_vendex') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.cuentas_por_cobrar TO app_vendex;
    END IF;
END $$;

COMMIT;

-- REPORTE huespedes (solo lectura, ejecutar aparte si hubo facturas a credito
-- guardadas antes del fix; esas filas tienen nota_venta_id de FACTURA sin proforma):
--   SELECT cpc.id, cpc.nota_venta_id, cpc.cliente_id, cpc.total, cpc.fecha_registro
--   FROM cuentas_por_cobrar cpc LEFT JOIN nota_venta_registro nv ON nv.id = cpc.nota_venta_id
--   WHERE cpc.factura_registro_id IS NULL AND nv.id IS NULL;
-- Cada fila devuelta es un credito de factura mal enlazado: conciliar a mano
-- (buscar su factura por cliente/total/fecha y setear factura_registro_id).

-- =====================================================================
-- SUPLEMENTO V33 — mensajes SRI a TEXT (eran VARCHAR(500))
-- Los detalles NO AUTORIZADO/DEVUELTA superan 500 chars y tumbaban
-- marcarResultado/actualizarEstado, dejando la cola atascada y re-enviando
-- correos cada ciclo. El codigo ademas trunca a 450 como cinturon.
-- =====================================================================

BEGIN;

-- Solo donde la columna existe (backups viejos pueden no traer mensaje_sri en factura_registro)
DO $$ DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT 'public.comprobante_pendiente_sri' AS t, 'ultimo_mensaje_sri' AS c
             UNION ALL SELECT 'public.comprobantes_electronicos', 'mensaje_sri'
             UNION ALL SELECT 'public.factura_registro', 'mensaje_sri'
             UNION ALL SELECT 'public.xml_enviados', 'mensaje_sri'
             UNION ALL SELECT 'public.nota_credito_registro', 'mensaje_sri'
             UNION ALL SELECT 'public.nota_debito_registro', 'mensaje_sri'
             UNION ALL SELECT 'public.guia_remision_registro', 'mensaje_sri'
             UNION ALL SELECT 'public.retencion_registro', 'mensaje_sri'
    LOOP
        IF EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = split_part(r.t, '.', 2)
                   AND column_name = r.c
                   AND data_type <> 'text') THEN
            EXECUTE format('ALTER TABLE %s ALTER COLUMN %I TYPE TEXT', r.t, r.c);
        END IF;
    END LOOP;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_vendex') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.comprobante_pendiente_sri TO app_vendex;
        GRANT SELECT, UPDATE ON TABLE public.comprobantes_electronicos TO app_vendex;
    END IF;
END $$;

COMMIT;

-- =====================================================================
-- SUPLEMENTO V34 — numero_autorizacion a VARCHAR(49) (drift: habia 37)
-- BDs creadas con DDL antiguo tienen comprobantes_electronicos y xml_enviados
-- en VARCHAR(37); el numero real del SRI (49 digitos) tumbaba actualizarEstado/
-- guardarEnvio y la pantalla quedaba en PENDIENTE aunque el SRI habia autorizado.
-- =====================================================================

BEGIN;

DO $$ DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT 'public.comprobantes_electronicos' AS t, 'numero_autorizacion' AS c
             UNION ALL SELECT 'public.xml_enviados', 'numero_autorizacion'
             UNION ALL SELECT 'public.factura_registro', 'numero_autorizacion'
             UNION ALL SELECT 'public.nota_credito_registro', 'numero_autorizacion'
             UNION ALL SELECT 'public.nota_debito_registro', 'numero_autorizacion'
             UNION ALL SELECT 'public.guia_remision_registro', 'numero_autorizacion'
             UNION ALL SELECT 'public.retencion_registro', 'numero_autorizacion'
    LOOP
        IF EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = split_part(r.t, '.', 2)
                   AND column_name = r.c
                   AND character_maximum_length IS NOT NULL
                   AND character_maximum_length < 49) THEN
            EXECUTE format('ALTER TABLE %s ALTER COLUMN %I TYPE VARCHAR(49)', r.t, r.c);
        END IF;
    END LOOP;
END $$;

COMMIT;
